name: Playwright CI Tests
on:
  workflow_dispatch
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]

jobs:

  test:

    timeout-minutes: 60
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd

    steps:
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps

    - name: Pull latest changes
      uses: actions/checkout@v4.2.2
      with:
        ref: github-pages-1

    - name: Copy actual dotenv file
      run: copy E:\Projects\js-projects\demo-framework-playwright\.env .env
      working-directory: ${{ github.workspace }}

    - name: Install dependencies
      run: npm i

    - name: Run tests
      run: npm run test

    - name: Generate allure report
      if: always()
      run: npm run allure:generate

    - name: Create tarball of report
      if: always()
      run: |
        cd allure-report
        tar -cvf github-pages.tar index.html

    - name: Upload artifact
      id: deployment
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: allure-report/github-pages.tar
        retention-days: 10
        if-no-files-found: error
      
  deploy:
    if: ${{ always() }}
    needs: test
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    # defaults:
    #   run:
    #     shell: cmd

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # with:
        #   artifact_name: allure-report.zip


    



