name: Playwright CI Tests
on:
  workflow_dispatch
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]

jobs:

  test:
    timeout-minutes: 60
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:


    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps

    - name: Pull latest changes
      uses: actions/checkout@v4.2.2
      with:
        ref: main

    - name: Copy actual dotenv file
      run: copy E:\Projects\js-projects\demo-framework-playwright\.env .env
      working-directory: ${{ github.workspace }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Generate allure report
      if: always()
      run: npm run allure:generate

    - name: Publish allure report
      uses: actions/upload-pages-artifact@v2
      if: ${{ !cancelled() }}
      with:
        # name: index.html
        path: allure-report
        retention-days: 10

  deploy:
    needs: test

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        if: ${{ !cancelled() }}
        uses: actions/deploy-pages@v4
        # with:
        #   artifact_name: index.html


    



